events{}

http{
    ## traffic control
    # rate limit
    limit_req_zone $binary_remote_addr zone=rag_index_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
        # concurrent request limit
    upstream rag-index-service {
        server orvexa-dc1-rag-index-service:8000;
    }
    # upstream rag-inference-service {
    #     server orvexa-dc1-rag-inference-service:8000;
    # }

    server{

        listen 80;
        absolute_redirect off;
        
        #concurrent_request_limit 10;
        # request size limit
        client_max_body_size 10m;
        # timeout
        proxy_connect_timeout 2s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
        send_timeout 10s;

        # retry
        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;

        # circuit breaker
        



        location /{
            default_type application/json;
            return 200 '{"message": "Hello from DC1"}';
        }

        location /api/ {
            
            # proxy_pass http://api:8080;
        }
        location = /rag-index {
            return 301 /rag-index/;
        }
        location /rag-index/ {
            limit_conn conn_limit 10;
            limit_req zone=rag_index_limit;
            proxy_pass http://rag-index-service/;
        }
        location /rag-inference/ {
            # proxy_pass http://rag-inference-service;
        }
    }
}