services:
  prometheus:
    image: prom/prometheus:latest

    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'

    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus

    networks:
      - observability_network
    restart: unless-stopped



  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - observability_network
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  observability_network:
    name: orvexa-observability-network
    external: true