events{}

http{
    upstream orvexa_dcs{
        server orvexa-dc1-gateway:80;
        # server orvexa-dc2-gateway:80;
    }

    server {
        listen 80;
      
        location / {
            proxy_pass http://orvexa_dcs;
        }
    }
}