services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - observability_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?pretty||exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
  
    networks:
      - observability_network
    depends_on:
      - elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    networks:
      - observability_network
    depends_on:
      - elasticsearch:
        condition: service_healthy

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
  #   user: "root"
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     #Docker container logs
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     #Docker metadata
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     #Filebeat read offsets/state
  #     - filebeat-data:/usr/share/filebeat/data
  #   networks:
  #     - observability_network
  #   depends_on:
  #     - logstash



volumes:
  elasticsearch-data:
  filebeat-data:

networks:
  observability_network:
    name: orvexa-observability-network
    driver: bridge