services:
  kafka:
    image: "${KAFKA_IMAGE:-apache/kafka:4.3.1}"
    restart: unless-stopped
    hostname: kafka

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      CLUSTER_ID: "${KAFKA_CLUSTER_ID:? KAFKA_CLUSTER_ID is required}"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
      
    networks:
      - event-network
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:19092 >/dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  event-network:
    external: true
    name: orvexa-event-network

volumes:
  kafka-data:
    driver: local